config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "flats#index"

  # this route will match urls like /flats/145, and put the variable id
  # it will put the id in  the params hash
  get 'flats/:id', to: "flats#show", as: "flat" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  # this action is linked to the root url ('/')
  def index
    # fetch data from api
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    json_text = open(url).read
    # parse JSON and save in instance variable so view has acces to it
    @flats = JSON.parse(json_text)
    # rails will automatically render the html file located at views/flats/index.html.erb
  end


  # this action is linked to urls like /flats/:id
  # for example /flats/145
  def show
    # fetch data from api
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    json_text = open(url).read
    # parse JSON
    flats = JSON.parse(json_text)
    # find the flat with the url provided by url and save to instance variable
    @flat = @flats.find { |flat| params["id"].to_i == flat["id"] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<ul>
  <%# (This is a comment) Iterate over all flats  %>
  <% @flats.each do |flat| %>
    <li>
      <%# Generate a link to the url flats/:id using the flat_path helper %>
      <%# The flat path helper requires an argument to know which id to point to %>
      <%= link_to "#{flat["name"]} - #{flat["price"]}€", flat_path(flat["id"]) %>
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<h1><%= @flat["name"] %></h1>
<h2><%= @flat["price"] %>€</h2>
<img src="<%= @flat["imageUrl"] %>" alt="" style="width: 300px;">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>